{% set name = "bigframes" %}
{% set version = "0.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bigframes-{{ version }}.tar.gz
  sha256: fb611afaa797e12cbfdcf3620aef277ab42dcabf47d502ea799a73db6ab72ffc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - cloudpickle >=2.0.0
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - geopandas >=0.12.2
    - google-auth >2.14.1,<3.0
    - google-cloud-bigquery-core >=3.10.0
# ModuleNotFoundError: No module named 'google.cloud.bigquery_storage_v1'
    - google-cloud-bigquery-storage >=2.0.0
    - google-cloud-functions >=1.10.1
    - google-cloud-bigquery-connection >=1.12.0
    - google-cloud-iam >=2.12.1
    - google-cloud-resource-manager >=1.10.3
    - google-cloud-storage >=2.0.0
    - ibis-framework-core >=7.1.0,<7.2.0
#ibis-framework 7.2.0 has requirement pins[gcs]<1,>=0.8.3, but you have pins 0.0.0.
    - ibis-framework >=7.1.0,<7.2.0
    - pins >=0.8.3,<1
    - gcsfs
#bigframes 0.18.0 has requirement ibis-framework[bigquery]<7.2.0dev,>=7.1.0, but you have ibis-framework 7.2.0.
    - ibis-bigquery >=7.1.0,<7.2.0
    - pandas >=1.5.0,<2.1.4
    - pydata-google-auth >=1.8.2
    - requests >=2.27.1
    - scikit-learn >=1.2.2
    - sqlalchemy >=1.4,<3.0
    - tabulate >=0.9.0
    - ipywidgets >=7.7.1
    - humanize >=4.6.0
#ibis-framework 6.2.0 has requirement pyarrow<13,>=2, but you have pyarrow 14.0.1.
#ibis-framework 7.1.0 has requirement sqlglot<20,>=18.12.0, but you have sqlglot 20.5.0.
    #- pyarrow >=2,<13
    - sqlglot >=18.12.0,<20

test:
  imports:
    - bigframes
    - third_party
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-dataframes
  summary: BigQuery DataFrames -- scalable analytics and machine learning with BigQuery
  license: BSD-4-Clause AND Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - third_party/bigframes_vendored/ibis/LICENSE.txt
    - third_party/bigframes_vendored/cpython/LICENSE
    - third_party/bigframes_vendored/pandas/LICENSE
    - third_party/bigframes_vendored/google_cloud_bigquery/LICENSE
    - third_party/bigframes_vendored/xgboost/LICENSE
    - third_party/bigframes_vendored/sklearn/COPYING

extra:
  recipe-maintainers:
    - rxm7706
