{% set name = "bigframes" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bigframes-{{ version }}.tar.gz
  sha256: 48331a1ec0e7d8eafc57dae1ccfeef8e5be1e726f3d90bf2210ce8877badf716

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - cloudpickle >=2.0.0
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - geopandas >=0.12.2
    - google-auth >2.14.1,<3.0
    - google-cloud-bigquery-core >=3.10.0
    - google-cloud-bigquery-storage >=2.0.0
    - google-cloud-functions >=1.10.1
    - google-cloud-bigquery-connection >=1.12.0
    - google-cloud-iam >=2.12.1
    - google-cloud-resource-manager >=1.10.3
    - google-cloud-storage >=2.0.0
    - ibis-framework >=6.2.0,<7.0.0
    - pandas >=1.5.0,<2.1.4
    - pydata-google-auth >=1.8.2
    - scikit-learn >=1.2.2
    - sqlalchemy >=1.4,<3.0
    - ipywidgets >=7.7.1
    - humanize >=4.6.0

test:
  imports:
    - bigframes
    - third_party
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-dataframes
  summary: BigQuery DataFrames -- scalable analytics and machine learning with BigQuery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
