{% set name = "bigframes" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bigframes-{{ version }}.tar.gz
  sha256: 161c97051266f74c100ecce4a5abea6027b034f1352fc6f89b89073b6b5434aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - cloudpickle >=2.0.0
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - geopandas >=0.12.2
    - google-auth >2.14.1,<3.0
    - google-cloud-bigquery-core >=3.10.0
    - google-cloud-bigquery-storage >=2.0.0
    - google-cloud-functions >=1.10.1
    - google-cloud-bigquery-connection >=1.12.0
    - google-cloud-iam >=2.12.1
    - google-cloud-resource-manager >=1.10.3
    - google-cloud-storage >=2.0.0
    - ibis-framework >=6.0.0,<=6.1.0
    - pandas >=1.5.0
    - pydata-google-auth >=1.8.2
    - scikit-learn >=1.2.2
    - sqlalchemy >=1.4,<3.0
    - ipywidgets >=7.7.1
    - humanize >=4.6.0

test:
  imports:
    - bigframes

about:
  home: https://github.com/googleapis/python-bigquery-dataframes
  summary: BigQuery DataFrames -- scalable analytics and machine learning with BigQuery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
